# Generated by Django 5.0.4 on 2024-05-01 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='sensor_description',
            field=models.CharField(default='Default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='sensor_name',
            field=models.CharField(default='Default', max_length=50),
            preserve_default=False,
        ),
    ]
