# Generated by Django 5.0.4 on 2024-05-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_sensor_sensor_description_sensor_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='device_description',
            field=models.CharField(default='This is some description about the device', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensordatatext',
            name='time',
            field=models.TimeField(),
        ),
    ]
